image: node:6

stages:
  - deploy

run:node
  stage: deploy
  before_script:
    - source .env
    - npm install
  script:
    - npm run build
    - mv dist public
  artifacts:
    paths:
    - public
  # only:
    # - master
