image: node:6

stages:
  - deploy

pages:
  stage: deploy
  before_script:
    - source .env
    - npm install
  script:
    - npm run build
    - mv dist public/dist
    - mv index.html public/
  artifacts:
    paths:
    - public
  only:
    - master
