image: node:6

stages:
  - test
  - deploy

cache:
  paths:
    - node_modules/
before_script:
  - source .env
  - npm install

test:
  variables:
    NODE_ENV: 'test'
  stage: test
  script:
    - npm run test

pages:
  variables:
    NODE_ENV: 'production'
  stage: deploy
  script:
    - npm run build
    - cp -r src public/
    - cp payomb* public/
    - mv dist public/
    - mv index.html public/
    - mv policy.html public/
    - find public/
  artifacts:
    paths:
    - public
  only:
    - master
