image: node:6

stages:
  - deploy

cache:
  paths:
    - node_modules/
before_script:
  - source .env
  - npm install

pages:
  stage: deploy
  script:
    - npm run build
    - mkdir public
    - mv dist public/
    - mv index.html public/
    - mv policy.html public/
    - find public/
  artifacts:
    paths:
    - public
  only:
    - master
